-- MySQL Script generated by MySQL Workbench
-- Mon Jan 17 01:11:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema task_force
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema task_force
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `task_force` DEFAULT CHARACTER SET utf8 ;
USE `task_force` ;

-- -----------------------------------------------------
-- Table `cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cities` (
  `id` INT UNSIGNED NOT NULL,
  `city` VARCHAR(80) NULL,
  `latitude` DECIMAL(8,6) NULL,
  `longtitude` DECIMAL(8,6) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `avatar` VARCHAR(80) NULL,
  `email` VARCHAR(80) NULL,
  `birthday` DATE NULL,
  `phone_number` VARCHAR(20) NULL,
  `telegram` VARCHAR(80) NULL,
  `resume` TEXT NULL,
  `account_registration_date` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `files` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(80) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tasks` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `start_time` DATETIME NULL,
  `short_name` TINYTEXT NULL,
  `resume` LONGTEXT NULL,
  `status` TINYINT NULL,
  `location_id` INT UNSIGNED NULL,
  `performer_id` INT UNSIGNED NULL,
  `customer_id` INT UNSIGNED NOT NULL,
  `files_id` INT UNSIGNED NULL,
  `budget` INT UNSIGNED NULL,
  `deadline` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `location_id_idx` (`location_id` ASC),
  INDEX `performer_id_idx` (`id` ASC, `performer_id` ASC),
  INDEX `customer_id_idx` (`customer_id` ASC),
  INDEX `files_id_idx` (`files_id` ASC),
  CONSTRAINT `location_id`
    FOREIGN KEY (`location_id`)
    REFERENCES `cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `performer_id`
    FOREIGN KEY (`id` , `performer_id`)
    REFERENCES `users` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `files_id`
    FOREIGN KEY (`files_id`)
    REFERENCES `files` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `specialization_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `specialization_list` (
  `specialization_id` INT UNSIGNED NOT NULL,
  `specialization_name` VARCHAR(80) NULL,
  PRIMARY KEY (`specialization_id`),
  UNIQUE INDEX `specialization_id_UNIQUE` (`specialization_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users_specialisations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users_specialisations` (
  `user_id` INT UNSIGNED NOT NULL,
  `specialisation_id` INT UNSIGNED NULL,
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `specialisation_id_idx` (`specialisation_id` ASC),
  CONSTRAINT `user_id_`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `specialisation_id`
    FOREIGN KEY (`specialisation_id`)
    REFERENCES `specialization_list` (`specialization_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pretenders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pretenders` (
  `user_id` INT UNSIGNED NOT NULL,
  `approved` TINYINT NULL DEFAULT 0,
  `task_id` INT UNSIGNED NULL,
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `price` INT UNSIGNED NULL,
  `pretender_comment` VARCHAR(45) NULL,
  `ocenka` SMALLINT(1) NULL,
  `client_comment` VARCHAR(45) NULL,
  UNIQUE INDEX `id_UNIQUE` (`user_id` ASC),
  INDEX `task_id_idx` (`task_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `candidate_id_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `task_id`
    FOREIGN KEY (`task_id`)
    REFERENCES `tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
